authors:
  probius:
    name: 探姬_Official
    description: 普通人罢了x
    avatar: https://nssctf.wdf.ink//img/WDTJ/202307251143264.png
  HelloCTF:
    name: HelloCTF_News
    description: HelloCTF_News_Official
    avatar: https://hello-ctf.com/assets/images/HelloCTF.png
  Cain:
    name: Cain
    description: Contributor
    avatar: https://raw.githubusercontent.com/N0wayBack/N0wayBack.github.io/main/images/member/Cain.png