name: Deploy to Github Pages and Update friends.md

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  deploy_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Automatically update friends.md
        run: |
          curl -o docs/AR/friends.md https://raw.githubusercontent.com/ProbiusOfficial/helloCTF-CTFerlink/main/output/friends.md
          curl -o docs/AR/index.md https://raw.githubusercontent.com/ProbiusOfficial/helloCTF-CTFerlink/main/output/friends.md

      - name: Automatically update event
        run: |
          curl -o docs/ET/Now_running.md https://raw.githubusercontent.com/ProbiusOfficial/Hello-CTFtime/main/Out/Now_running.md
          curl -o docs/ET/Past_events.md https://raw.githubusercontent.com/ProbiusOfficial/Hello-CTFtime/main/Out/Past_events.md
          curl -o docs/ET/Upcoming_events.md https://raw.githubusercontent.com/ProbiusOfficial/Hello-CTFtime/main/Out/Upcoming_events.md

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force

      - name: Check for changes
        id: check_changes
        run: |
          git add docs/AR/friends.md
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.CHANGES == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically update
